export const products = [
  {
    id: "gid://shopify/Product/8093031825693",
    availableForSale: true,
    createdAt: "2023-01-18T00:20:24Z",
    updatedAt: "2023-01-18T00:20:27Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">This essential backpack is made of a PVC-backed tightly woven nylon for extreme durability. This textile is water resistant and easy to clean and maintain. This backpack has a deep, boxy shape with a large front zippered pouch and padded adjustable straps. Perfect for day to day use on campus or for traveling.</p>\n</div>\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">• Unisex<br data-mce-fragment="1">• 1 main zippered compartment<br data-mce-fragment="1">• 1 zippered front pouch<br data-mce-fragment="1">• Water Resistant<br></p>\n<section data-section="styled_with_collection" data-mce-fragment="1">72% PVC/ 28% NYLON</section>\n</div>',
    description:
      "This essential backpack is made of a PVC-backed tightly woven nylon for extreme durability. This textile is water resistant and easy to clean and maintain. This backpack has a deep, boxy shape with a large front zippered pouch and padded adjustable straps. Perfect for day to day use on campus or for traveling. • Unisex• 1 main zippered compartment• 1 zippered front pouch• Water Resistant 72% PVC/ 28% NYLON",
    handle: "backpack",
    productType: "Accessories",
    title: "Backpack",
    vendor: "RealSpiffy",
    publishedAt: "2023-01-18T00:20:25Z",
    onlineStoreUrl: null,
    options: [
      {
        id: "gid://shopify/ProductOption/10280503345437",
        name: "Color",
        values: [
          {
            value: "Black",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "Grey",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
        ],
        type: {
          name: "ProductOption",
          kind: "OBJECT",
          fieldBaseTypes: {
            name: "String",
            values: "String",
          },
          implementsNode: true,
        },
      },
    ],
    images: [
      {
        id: "gid://shopify/ProductImage/40298319216925",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/RNP500-BLACKBLACK-1.webp?v=1674001226",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298319249693",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/RNP500-BLACKBLACK-2.webp?v=1674001226",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298319315229",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/RNP500-BLACKBLACK-3.webp?v=1674001226",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/44244122599709",
        title: "Black",
        price: {
          amount: "48.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "48.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298319216925",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/RNP500-BLACKBLACK-1.webp?v=1674001226",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44244122632477",
        title: "Grey",
        price: {
          amount: "48.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "48.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: false,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298319216925",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/RNP500-BLACKBLACK-1.webp?v=1674001226",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    type: {
      name: "Product",
      kind: "OBJECT",
      fieldBaseTypes: {
        availableForSale: "Boolean",
        createdAt: "DateTime",
        description: "String",
        descriptionHtml: "HTML",
        handle: "String",
        id: "ID",
        images: "ImageConnection",
        onlineStoreUrl: "URL",
        options: "ProductOption",
        productType: "String",
        publishedAt: "DateTime",
        title: "String",
        updatedAt: "DateTime",
        variants: "ProductVariantConnection",
        vendor: "String",
      },
      implementsNode: true,
    },
    hasNextPage: {
      value: true,
    },
    hasPreviousPage: false,
    variableValues: {
      handle: "accessories",
    },
  },
  {
    id: "gid://shopify/Product/8093019406621",
    availableForSale: true,
    createdAt: "2023-01-17T23:58:12Z",
    updatedAt: "2023-01-17T23:58:28Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">This 5 panel style hat features a <meta charset="utf-8">breathable cotton base. This hat has a mid-profile crown, tonal flat bill and adjustable closure. </p>\n</div>\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">• Unisex<br></p>\n<p data-mce-fragment="1">Poly/Spandex (82% Polyester / 18% Spandex)</p>\n</div>',
    description:
      "This 5 panel style hat features a breathable cotton base. This hat has a mid-profile crown, tonal flat bill and adjustable closure. • Unisex Poly/Spandex (82% Polyester / 18% Spandex)",
    handle: "5-panel-hat",
    productType: "Accessories",
    title: "5 Panel Hat",
    vendor: "RealSpiffy",
    publishedAt: "2023-01-17T23:58:13Z",
    onlineStoreUrl: null,
    options: [
      {
        id: "gid://shopify/ProductOption/10280488370461",
        name: "Color",
        values: [
          {
            value: "Black",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "Grey",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "White",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
        ],
        type: {
          name: "ProductOption",
          kind: "OBJECT",
          fieldBaseTypes: {
            name: "String",
            values: "String",
          },
          implementsNode: true,
        },
      },
    ],
    images: [
      {
        id: "gid://shopify/ProductImage/40298181034269",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/black-side.webp?v=1673999893",
        altText: null,
        width: 1500,
        height: 2100,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298181165341",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/darkgrey-side.webp?v=1673999894",
        altText: null,
        width: 1500,
        height: 2100,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298181132573",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/IMG_1509.webp?v=1673999893",
        altText: null,
        width: 750,
        height: 1125,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/44244066369821",
        title: "Black",
        price: {
          amount: "28.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "28.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298181034269",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/black-side.webp?v=1673999893",
          altText: null,
          width: 1500,
          height: 2100,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44244066435357",
        title: "Grey",
        price: {
          amount: "28.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "28.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298181165341",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/darkgrey-side.webp?v=1673999894",
          altText: null,
          width: 1500,
          height: 2100,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44244066500893",
        title: "White",
        price: {
          amount: "28.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "28.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298181132573",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/IMG_1509.webp?v=1673999893",
          altText: null,
          width: 750,
          height: 1125,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "White",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    type: {
      name: "Product",
      kind: "OBJECT",
      fieldBaseTypes: {
        availableForSale: "Boolean",
        createdAt: "DateTime",
        description: "String",
        descriptionHtml: "HTML",
        handle: "String",
        id: "ID",
        images: "ImageConnection",
        onlineStoreUrl: "URL",
        options: "ProductOption",
        productType: "String",
        publishedAt: "DateTime",
        title: "String",
        updatedAt: "DateTime",
        variants: "ProductVariantConnection",
        vendor: "String",
      },
      implementsNode: true,
    },
    hasNextPage: {
      value: true,
    },
    hasPreviousPage: {
      value: true,
    },
    variableValues: {
      handle: "accessories",
    },
  },
  {
    id: "gid://shopify/Product/8093002662173",
    availableForSale: true,
    createdAt: "2023-01-17T23:45:35Z",
    updatedAt: "2023-01-17T23:50:03Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">Basic cuff beanie made from 100% acrylic. Perfect for the chilly winters.</p>\n</div>\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">• 100% Acrylic<br data-mce-fragment="1">• Unisex<br></p>\n</div>',
    description:
      "Basic cuff beanie made from 100% acrylic. Perfect for the chilly winters. • 100% Acrylic• Unisex",
    handle: "beanie",
    productType: "Accessories",
    title: "Beanie",
    vendor: "RealSpiffy",
    publishedAt: "2023-01-17T23:45:35Z",
    onlineStoreUrl: null,
    options: [
      {
        id: "gid://shopify/ProductOption/10280467398941",
        name: "Color",
        values: [
          {
            value: "Black",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "Grey",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "White",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
        ],
        type: {
          name: "ProductOption",
          kind: "OBJECT",
          fieldBaseTypes: {
            name: "String",
            values: "String",
          },
          implementsNode: true,
        },
      },
    ],
    images: [
      {
        id: "gid://shopify/ProductImage/40298092921117",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/black_2_27886243-8a30-4694-8440-c09680bedf29.webp?v=1673999136",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298092888349",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/beanie-blackk.webp?v=1673999136",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298112745757",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/Heather_791aa312-9e2a-4325-9521-a59f7d3320e9.jpg?v=1673999386",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298113073437",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/beanie_bleach.webp?v=1673999388",
        altText: null,
        width: 1100,
        height: 1650,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/44243976192285",
        title: "Black",
        price: {
          amount: "0.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "0.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298092921117",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/black_2_27886243-8a30-4694-8440-c09680bedf29.webp?v=1673999136",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243976225053",
        title: "Grey",
        price: {
          amount: "0.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "0.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298112745757",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/Heather_791aa312-9e2a-4325-9521-a59f7d3320e9.jpg?v=1673999386",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243976257821",
        title: "White",
        price: {
          amount: "0.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "0.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40298113073437",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/beanie_bleach.webp?v=1673999388",
          altText: null,
          width: 1100,
          height: 1650,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "White",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    type: {
      name: "Product",
      kind: "OBJECT",
      fieldBaseTypes: {
        availableForSale: "Boolean",
        createdAt: "DateTime",
        description: "String",
        descriptionHtml: "HTML",
        handle: "String",
        id: "ID",
        images: "ImageConnection",
        onlineStoreUrl: "URL",
        options: "ProductOption",
        productType: "String",
        publishedAt: "DateTime",
        title: "String",
        updatedAt: "DateTime",
        variants: "ProductVariantConnection",
        vendor: "String",
      },
      implementsNode: true,
    },
    hasNextPage: {
      value: true,
    },
    hasPreviousPage: {
      value: true,
    },
    variableValues: {
      handle: "accessories",
    },
  },
  {
    id: "gid://shopify/Product/8092986736925",
    availableForSale: true,
    createdAt: "2023-01-17T23:36:00Z",
    updatedAt: "2023-01-17T23:47:09Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1"><span data-mce-fragment="1">A winter staple. This unisex glove fits most sizes and is made of our insulating acrylic yarn to keep your hands warm. Features a ribbed cuff for a secure fit. </span></p>\n<p data-mce-fragment="1">• Unisex</p>\n<p data-mce-fragment="1">• Made in U.S.A.</p>\n</div>\n<div class="mt-3" data-mce-fragment="1">\n<p data-mce-fragment="1">100% Acrylic</p>\n</div>',
    description:
      "A winter staple. This unisex glove fits most sizes and is made of our insulating acrylic yarn to keep your hands warm. Features a ribbed cuff for a secure fit. • Unisex • Made in U.S.A. 100% Acrylic",
    handle: "gloves",
    productType: "Accessories",
    title: "Gloves",
    vendor: "RealSpiffy",
    publishedAt: "2023-01-17T23:36:01Z",
    onlineStoreUrl: null,
    options: [
      {
        id: "gid://shopify/ProductOption/10280450949405",
        name: "Color",
        values: [
          {
            value: "Black",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "Grey",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
        ],
        type: {
          name: "ProductOption",
          kind: "OBJECT",
          fieldBaseTypes: {
            name: "String",
            values: "String",
          },
          implementsNode: true,
        },
      },
    ],
    images: [
      {
        id: "gid://shopify/ProductImage/40298042917149",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/glove01-blackf.webp?v=1673998562",
        altText: null,
        width: 1333,
        height: 2000,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40298042851613",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/glove01-heathergreyf.webp?v=1673998562",
        altText: null,
        width: 1100,
        height: 1650,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/44243950371101",
        title: "Black",
        price: {
          amount: "10.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "10.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: {
          amount: "14.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        compareAtPriceV2: {
          amount: "14.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        image: {
          id: "gid://shopify/ProductImage/40298042917149",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/glove01-blackf.webp?v=1673998562",
          altText: null,
          width: 1333,
          height: 2000,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243950403869",
        title: "Grey",
        price: {
          amount: "10.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "10.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: {
          amount: "14.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        compareAtPriceV2: {
          amount: "14.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        image: {
          id: "gid://shopify/ProductImage/40298042917149",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/glove01-blackf.webp?v=1673998562",
          altText: null,
          width: 1333,
          height: 2000,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    type: {
      name: "Product",
      kind: "OBJECT",
      fieldBaseTypes: {
        availableForSale: "Boolean",
        createdAt: "DateTime",
        description: "String",
        descriptionHtml: "HTML",
        handle: "String",
        id: "ID",
        images: "ImageConnection",
        onlineStoreUrl: "URL",
        options: "ProductOption",
        productType: "String",
        publishedAt: "DateTime",
        title: "String",
        updatedAt: "DateTime",
        variants: "ProductVariantConnection",
        vendor: "String",
      },
      implementsNode: true,
    },
    hasNextPage: {
      value: true,
    },
    hasPreviousPage: {
      value: true,
    },
    variableValues: {
      handle: "accessories",
    },
  },
  {
    id: "gid://shopify/Product/8092931031325",
    availableForSale: true,
    createdAt: "2023-01-17T23:10:06Z",
    updatedAt: "2023-01-17T23:49:20Z",
    descriptionHtml:
      '<p><meta charset="utf-8"><span data-mce-fragment="1">With extra cushion on the pad of the foot and a lighter knit on the top, this sock is sure to keep your feet dry and comfortable without crowding your foot. The mid-height on the rib can be worn either pulled up or scrunched down for a more causal fit, the foldover hem will make sure it stays put. A deep Y-Gusset makes the heel deeper to assure it won\'t drift during the day. These socks have been Garment Dyed to match or mix and match with your favorite basics.</span></p>\n<p><span data-mce-fragment="1"><meta charset="utf-8">• Unisex<br>• Made in U.S.A.<br><br>79% Cotton<br>20% Nylon<br>1% Spandex</span></p>',
    description:
      "With extra cushion on the pad of the foot and a lighter knit on the top, this sock is sure to keep your feet dry and comfortable without crowding your foot. The mid-height on the rib can be worn either pulled up or scrunched down for a more causal fit, the foldover hem will make sure it stays put. A deep Y-Gusset makes the heel deeper to assure it won't drift during the day. These socks have been Garment Dyed to match or mix and match with your favorite basics. • Unisex• Made in U.S.A.79% Cotton20% Nylon1% Spandex",
    handle: "socks",
    productType: "Accessories",
    title: "Socks",
    vendor: "RealSpiffy",
    publishedAt: "2023-01-17T23:10:08Z",
    onlineStoreUrl: null,
    options: [
      {
        id: "gid://shopify/ProductOption/10280390951197",
        name: "Color",
        values: [
          {
            value: "Black",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "Grey",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "White",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
        ],
        type: {
          name: "ProductOption",
          kind: "OBJECT",
          fieldBaseTypes: {
            name: "String",
            values: "String",
          },
          implementsNode: true,
        },
      },
      {
        id: "gid://shopify/ProductOption/10280429519133",
        name: "Size",
        values: [
          {
            value: "S",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "M",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
          {
            value: "L",
            type: {
              name: "String",
              kind: "SCALAR",
            },
          },
        ],
        type: {
          name: "ProductOption",
          kind: "OBJECT",
          fieldBaseTypes: {
            name: "String",
            values: "String",
          },
          implementsNode: true,
        },
      },
    ],
    images: [
      {
        id: "gid://shopify/ProductImage/40297875865885",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_black.jpg?v=1673997008",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40297875931421",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/unisock_grey.jpg?v=1673997009",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductImage/40297875833117",
        src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_white.webp?v=1673997008",
        altText: null,
        width: 1500,
        height: 2250,
        type: {
          name: "Image",
          kind: "OBJECT",
          fieldBaseTypes: {
            altText: "String",
            height: "Int",
            id: "ID",
            url: "URL",
            width: "Int",
          },
          implementsNode: false,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/44243919307037",
        title: "Black / S",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875865885",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_black.jpg?v=1673997008",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "S",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: false,
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919339805",
        title: "Black / M",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875865885",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_black.jpg?v=1673997008",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "M",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919372573",
        title: "Black / L",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875865885",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_black.jpg?v=1673997008",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "L",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919438109",
        title: "Grey / S",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875931421",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/unisock_grey.jpg?v=1673997009",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "S",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919470877",
        title: "Grey / M",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875931421",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/unisock_grey.jpg?v=1673997009",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "M",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919503645",
        title: "Grey / L",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875931421",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/unisock_grey.jpg?v=1673997009",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "Grey",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "L",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919569181",
        title: "White / S",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875833117",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_white.webp?v=1673997008",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "White",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "S",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919601949",
        title: "White / M",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: true,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875833117",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_white.webp?v=1673997008",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "White",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "M",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: {
          value: true,
        },
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
      {
        id: "gid://shopify/ProductVariant/44243919634717",
        title: "White / L",
        price: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        priceV2: {
          amount: "8.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: {
              amount: "Decimal",
              currencyCode: "CurrencyCode",
            },
            implementsNode: false,
          },
        },
        weight: 0,
        available: false,
        sku: "",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "gid://shopify/ProductImage/40297875833117",
          src: "https://cdn.shopify.com/s/files/1/0694/5013/7885/products/socks_white.webp?v=1673997008",
          altText: null,
          width: 1500,
          height: 2250,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              url: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Color",
            value: "White",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
          {
            name: "Size",
            value: "L",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: {
                name: "String",
                value: "String",
              },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "MoneyV2",
            id: "ID",
            image: "Image",
            price: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
        hasNextPage: false,
        hasPreviousPage: {
          value: true,
        },
        variableValues: {
          handle: "accessories",
        },
      },
    ],
    type: {
      name: "Product",
      kind: "OBJECT",
      fieldBaseTypes: {
        availableForSale: "Boolean",
        createdAt: "DateTime",
        description: "String",
        descriptionHtml: "HTML",
        handle: "String",
        id: "ID",
        images: "ImageConnection",
        onlineStoreUrl: "URL",
        options: "ProductOption",
        productType: "String",
        publishedAt: "DateTime",
        title: "String",
        updatedAt: "DateTime",
        variants: "ProductVariantConnection",
        vendor: "String",
      },
      implementsNode: true,
    },
    hasNextPage: false,
    hasPreviousPage: {
      value: true,
    },
    variableValues: {
      handle: "accessories",
    },
  },
];
